fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Microsoft]
      # - id: clang-tidy
      #   args: [--checks=modernize-*,performance-*,readability-*,portability-*, --warnings-as-errors=*]
